In [4]:
import numpy as np
np.array(2)

array(2)

In [12]:
# From list: 1d array
my_list = [10, 20, 30]
a = np.array(my_list)

print(a.shape)
print(a.dtype)

(3,)
int64


In [13]:
# From list: 2d array

list_of_lists =  [[5, 10, 15], [20, 25, 30], [35, 40, 45]]
b = np.array(list_of_lists)

print(b.shape)
print(b.dtype)

(3, 3)
int64


In [15]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Linspace: Return evenly spaced numbers over a specified interval.
linspace(start, stop, num=50, endpoint=True, retstep=False)

Will return num number of values
Equally spaced samples in the closed interval [start, stop] or the half-open interval [start, stop)
Closed or half-open interval depends on whether 'endpoint' is True or False.

In [19]:
# divide into 7 interval from 0 to 10
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [20]:
# 10 random integers upto 50 (exclusive). This makes the start value default to 0.
# The size parameter dictates the return array shape

np.random.randint(50, size=(3,4))

array([[38, 41, 20,  1],
       [29, 40,  1, 44],
       [39,  1, 11, 28]])

In [21]:
# 10 random integers between 4 (inclusive) to 40 (exclusive)

np.random.randint(4, 40, 10)

array([13, 30, 16, 15, 31, 20, 35, 34,  8, 35])

In [22]:
# random number (standard normal distribution) array of shape (2, 3)

print (np.random.randn(2, 3))

[[-0.58020569 -1.43300711 -0.83925326]
 [-0.69595333  2.10232213 -0.04559119]]


In [23]:
# random number (uniform distribution) array of shape (5, 5)

np.random.rand(3, 4)

array([[0.36825397, 0.8985671 , 0.09547059, 0.12890592],
       [0.21629143, 0.24669675, 0.2881756 , 0.19022049],
       [0.77241924, 0.15673239, 0.97238083, 0.08534291]])